name: subgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg>=6.0,<8.0
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - torchcodec==0.7.0
      - pyannote.audio==4.0.7
      - faster-whisper==1.2.1
      - pyyaml>=6.0.0
      - pytest>=8.0.0
